version: "3"
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - "9000:9000"
    volumes:
      - "./database/01-event-table.sql:/docker-entrypoint-initdb.d/1.sql"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1s
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
